characters = [
  {
    "id": "levi-ackerman", "name": "Levi Ackerman", "gender": "male", "series": "Attack on Titan",
    "creator": "Hajime Isayama", "characterDesigner": None, "studio": "Wit Studio / MAPPA", "franchise": "Attack on Titan",
    "aliases": [], "publisher": "Kodansha", "firstAppearance": "2009 (manga)", "collection": "anime",
    "visual_traits": ["Sharp jaw", "Narrow eyes", "Minimal expression", "Short dark undercut"],
    "design_language": ["Precision", "Discipline", "Efficiency"],
    "shape_language": "Triangles and rectangles",
    "primary_colors": ["#3B3F45", "#C8C2B4", "#5D4A36"],
    "silhouette": "Slim vertical", "archetype": "The Ace", "temperament": "Controlled",
    "keywords": ["stoic", "compact", "elite", "clean"],
    "description": "A design built on subtraction: nothing decorative, nothing loose, nothing wasted.",
    "profile": { "faceLength": 0.62, "jawSharpness": 0.85, "eyeNarrowness": 0.9, "browWeight": 0.7, "hairDarkness": 0.9, "hairVolume": 0.25, "expressionNeutrality": 0.95, "contrast": 0.7, "angularity": 0.85, "glasses": 0.0, "warmth": 0.5 },
    "facialMetrics": { "faceShape": 0.82, "jawWidthRatio": 0.7, "jawAngle": 0.69, "chinLengthRatio": 0.47, "chinSharpness": 0.67, "foreheadWidthRatio": 0.37, "foreheadHeightRatio": 0.61, "cheekboneWidthRatio": 0.81, "faceHeightRatio": 0.66, "eyeSizeRatio": 0.31, "eyeSpacingRatio": 0.55, "eyeTilt": 0.74, "eyeRoundness": 0.46, "eyebrowThickness": 0.62, "eyebrowCurve": 0.53, "noseLengthRatio": 0.54, "noseWidthRatio": 0.6, "mouthWidthRatio": 0.33, "lipThickness": 0.48, "earSizeRatio": 0.7, "hairlineHeight": 0.34, "neckWidthRatio": 0.62, "stylizationIndex": 0.26 },
    "design_breakdown": { "communicates": ["Precision", "Control", "Calmness", "Efficiency"], "through": ["narrow eyes", "compact silhouette", "muted palette", "clean geometry"] }
  },
  {
    "id": "gojo-satoru", "name": "Gojo Satoru", "gender": "male", "series": "Jujutsu Kaisen",
    "creator": "Gege Akutami", "characterDesigner": None, "studio": "MAPPA", "franchise": "Jujutsu Kaisen",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "2018 (manga)", "collection": "anime",
    "visual_traits": ["Blindfold/eyewear", "Tall silhouette", "White spiked hair", "Confident smirk"],
    "design_language": ["Overwhelming ease", "Mystery", "Play"],
    "shape_language": "Vertical rectangles with triangular hair",
    "primary_colors": ["#FFFFFF", "#101018", "#59C1E8"],
    "silhouette": "Tall vertical", "archetype": "The Untouchable Mentor", "temperament": "Playful",
    "keywords": ["masked eyes", "tall", "white hair", "smug"],
    "description": "Covered eyes force the design to act through posture and mouth — confidence drawn without pupils.",
    "profile": { "faceLength": 0.7, "jawSharpness": 0.7, "eyeNarrowness": 0.6, "browWeight": 0.3, "hairDarkness": 0.05, "hairVolume": 0.7, "expressionNeutrality": 0.35, "contrast": 0.85, "angularity": 0.7, "glasses": 0.9, "warmth": 0.5 },
    "facialMetrics": { "faceShape": 0.63, "jawWidthRatio": 0.6, "jawAngle": 0.62, "chinLengthRatio": 0.56, "chinSharpness": 0.54, "foreheadWidthRatio": 0.54, "foreheadHeightRatio": 0.64, "cheekboneWidthRatio": 0.62, "faceHeightRatio": 0.64, "eyeSizeRatio": 0.54, "eyeSpacingRatio": 0.59, "eyeTilt": 0.51, "eyeRoundness": 0.64, "eyebrowThickness": 0.25, "eyebrowCurve": 0.54, "noseLengthRatio": 0.42, "noseWidthRatio": 0.35, "mouthWidthRatio": 0.42, "lipThickness": 0.42, "earSizeRatio": 0.44, "hairlineHeight": 0.55, "neckWidthRatio": 0.44, "stylizationIndex": 0.49 },
    "design_breakdown": { "communicates": ["Effortless power", "Unreadability", "Charisma"], "through": ["hidden eyes", "high-contrast palette", "loose posture over tall frame", "a smile doing the acting"] }
  },
  {
    "id": "sasuke-uchiha", "name": "Sasuke Uchiha", "gender": "male", "series": "Naruto",
    "creator": "Masashi Kishimoto", "characterDesigner": None, "studio": "Pierrot", "franchise": "Naruto",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "1999 (manga)", "collection": "anime",
    "visual_traits": ["Angular face", "Narrow dark eyes", "Raven hair with back spikes", "Cool detachment"],
    "design_language": ["Rivalry", "Elegance", "Distance"],
    "shape_language": "Triangles",
    "primary_colors": ["#1B2430", "#3E4C63", "#8A0F1E"],
    "silhouette": "Sharp, wind-swept", "archetype": "The Rival", "temperament": "Aloof",
    "keywords": ["brooding", "prodigy", "dark hair", "sharp"],
    "description": "The visual opposite of his rival by construction: cool hues, downward lines, closed posture.",
    "profile": { "faceLength": 0.65, "jawSharpness": 0.8, "eyeNarrowness": 0.8, "browWeight": 0.6, "hairDarkness": 0.95, "hairVolume": 0.6, "expressionNeutrality": 0.8, "contrast": 0.7, "angularity": 0.8, "warmth": 0.3, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.74, "jawWidthRatio": 0.69, "jawAngle": 0.7, "chinLengthRatio": 0.57, "chinSharpness": 0.65, "foreheadWidthRatio": 0.49, "foreheadHeightRatio": 0.58, "cheekboneWidthRatio": 0.76, "faceHeightRatio": 0.66, "eyeSizeRatio": 0.33, "eyeSpacingRatio": 0.44, "eyeTilt": 0.72, "eyeRoundness": 0.47, "eyebrowThickness": 0.5, "eyebrowCurve": 0.39, "noseLengthRatio": 0.52, "noseWidthRatio": 0.39, "mouthWidthRatio": 0.31, "lipThickness": 0.46, "earSizeRatio": 0.35, "hairlineHeight": 0.51, "neckWidthRatio": 0.61, "stylizationIndex": 0.6 },
    "design_breakdown": { "communicates": ["Talent", "Isolation", "Contained intensity"], "through": ["cool palette against a warm-hero rival", "triangular hair mass", "half-lidded eye frames", "minimal costume ornament"] }
  },
  {
    "id": "mikasa-ackerman", "name": "Mikasa Ackerman", "gender": "female", "series": "Attack on Titan",
    "creator": "Hajime Isayama", "characterDesigner": None, "studio": "Wit Studio / MAPPA", "franchise": "Attack on Titan",
    "aliases": [], "publisher": "Kodansha", "firstAppearance": "2009 (manga)", "collection": "anime",
    "visual_traits": ["Level gaze", "Short black bob", "Red scarf", "Athletic frame"],
    "design_language": ["Loyalty", "Lethality", "Restraint"],
    "shape_language": "Rectangles with one soft accent",
    "primary_colors": ["#2E2E34", "#B8AC98", "#A3272E"],
    "silhouette": "Balanced vertical", "archetype": "The Protector", "temperament": "Steadfast",
    "keywords": ["scarf", "calm", "strong", "bob cut"],
    "description": "One warm accessory carries the entire emotional backstory; everything else stays soldier-plain.",
    "profile": { "faceLength": 0.55, "jawSharpness": 0.6, "eyeNarrowness": 0.65, "browWeight": 0.55, "hairDarkness": 0.95, "hairVolume": 0.4, "expressionNeutrality": 0.85, "symmetry": 0.75, "contrast": 0.6, "angularity": 0.6, "warmth": 0.5, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.7, "jawWidthRatio": 0.62, "jawAngle": 0.49, "chinLengthRatio": 0.5, "chinSharpness": 0.54, "foreheadWidthRatio": 0.55, "foreheadHeightRatio": 0.6, "cheekboneWidthRatio": 0.57, "faceHeightRatio": 0.5, "eyeSizeRatio": 0.52, "eyeSpacingRatio": 0.64, "eyeTilt": 0.48, "eyeRoundness": 0.46, "eyebrowThickness": 0.47, "eyebrowCurve": 0.52, "noseLengthRatio": 0.53, "noseWidthRatio": 0.52, "mouthWidthRatio": 0.34, "lipThickness": 0.55, "earSizeRatio": 0.15, "hairlineHeight": 0.38, "neckWidthRatio": 0.47, "stylizationIndex": 0.34 },
    "design_breakdown": { "communicates": ["Devotion", "Competence", "Quiet intensity"], "through": ["the single red scarf against muted uniform", "level symmetrical features", "practical hair", "still posture"] }
  },
  {
    "id": "sung-jinwoo", "name": "Sung Jinwoo", "gender": "male", "series": "Solo Leveling",
    "creator": "Chugong", "characterDesigner": "Dubu (Redice Studio)", "studio": "A-1 Pictures", "franchise": "Solo Leveling",
    "aliases": [], "publisher": "D&C Media / Kakao", "firstAppearance": "2016 (web novel)", "collection": "anime",
    "visual_traits": ["Sharp long face", "Piercing narrow eyes", "Black layered hair", "Shadowed palette"],
    "design_language": ["Ascension", "Menace", "Solitude"],
    "shape_language": "Long triangles",
    "primary_colors": ["#0E1116", "#5A32A8", "#B9C2CF"],
    "silhouette": "Long vertical blade", "archetype": "The Ascendant", "temperament": "Resolved",
    "keywords": ["shadow", "hunter", "purple", "sharp"],
    "description": "A design that literally darkens as the character grows — value scripting as power curve.",
    "profile": { "faceLength": 0.8, "jawSharpness": 0.85, "eyeNarrowness": 0.85, "browWeight": 0.6, "hairDarkness": 0.95, "hairVolume": 0.55, "expressionNeutrality": 0.75, "contrast": 0.8, "angularity": 0.85, "warmth": 0.2, "symmetry": 0.6, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.83, "jawWidthRatio": 0.81, "jawAngle": 0.73, "chinLengthRatio": 0.69, "chinSharpness": 0.74, "foreheadWidthRatio": 0.49, "foreheadHeightRatio": 0.65, "cheekboneWidthRatio": 0.67, "faceHeightRatio": 0.84, "eyeSizeRatio": 0.39, "eyeSpacingRatio": 0.5, "eyeTilt": 0.75, "eyeRoundness": 0.35, "eyebrowThickness": 0.62, "eyebrowCurve": 0.3, "noseLengthRatio": 0.62, "noseWidthRatio": 0.48, "mouthWidthRatio": 0.46, "lipThickness": 0.29, "earSizeRatio": 0.21, "hairlineHeight": 0.51, "neckWidthRatio": 0.45, "stylizationIndex": 0.35 },
    "design_breakdown": { "communicates": ["Growth into power", "Danger", "Focus"], "through": ["progressively darker palette", "elongated face and frame", "eye highlights removed at peak moments", "monochrome with one violet accent"] }
  },
  {
    "id": "tanjiro-kamado", "name": "Tanjiro Kamado", "gender": "male", "series": "Demon Slayer",
    "creator": "Koyoharu Gotouge", "characterDesigner": None, "studio": "ufotable", "franchise": "Demon Slayer",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "2016 (manga)", "collection": "anime",
    "visual_traits": ["Soft rounded eyes", "Forehead scar", "Checked haori", "Hanafuda earrings"],
    "design_language": ["Kindness", "Inheritance", "Resolve"],
    "shape_language": "Circles on squares",
    "primary_colors": ["#1E5E4E", "#101010", "#C33A32"],
    "silhouette": "Compact with layered haori", "archetype": "The Gentle Hero", "temperament": "Warm",
    "keywords": ["kind", "scar", "checked pattern", "earrings"],
    "description": "Every element is inherited — the design argues that gentleness can be armor.",
    "profile": { "faceLength": 0.45, "jawSharpness": 0.35, "eyeNarrowness": 0.25, "browWeight": 0.5, "hairDarkness": 0.8, "hairVolume": 0.55, "expressionNeutrality": 0.3, "symmetry": 0.65, "contrast": 0.6, "angularity": 0.35, "warmth": 0.75, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.47, "jawWidthRatio": 0.47, "jawAngle": 0.4, "chinLengthRatio": 0.55, "chinSharpness": 0.36, "foreheadWidthRatio": 0.59, "foreheadHeightRatio": 0.54, "cheekboneWidthRatio": 0.43, "faceHeightRatio": 0.53, "eyeSizeRatio": 0.78, "eyeSpacingRatio": 0.48, "eyeTilt": 0.48, "eyeRoundness": 0.86, "eyebrowThickness": 0.48, "eyebrowCurve": 0.56, "noseLengthRatio": 0.49, "noseWidthRatio": 0.35, "mouthWidthRatio": 0.48, "lipThickness": 0.67, "earSizeRatio": 0.46, "hairlineHeight": 0.58, "neckWidthRatio": 0.28, "stylizationIndex": 0.45 },
    "design_breakdown": { "communicates": ["Warmth", "Duty", "Endurance without hardness"], "through": ["rounded eye frames", "family-inherited costume elements", "a scar placed where the eye lands second", "warm-against-dark palette"] }
  },
  {
    "id": "naruto-uzumaki", "name": "Naruto Uzumaki", "gender": "male", "series": "Naruto",
    "creator": "Masashi Kishimoto", "characterDesigner": None, "studio": "Pierrot", "franchise": "Naruto",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "1999 (manga)", "collection": "anime",
    "visual_traits": ["Round face", "Wide bright eyes", "Spiky blond hair", "Whisker marks", "Grin"],
    "design_language": ["Refusal to be ignored", "Optimism", "Energy"],
    "shape_language": "Triangles on circles",
    "primary_colors": ["#F6841F", "#1B3B6F", "#FFD75E"],
    "silhouette": "Spiky and open", "archetype": "The Underdog", "temperament": "Exuberant",
    "keywords": ["orange", "loud", "spiky", "grin"],
    "description": "Orange is the argument: a shunned child dressed in the colour that cannot be overlooked.",
    "profile": { "faceLength": 0.4, "jawSharpness": 0.4, "eyeNarrowness": 0.2, "browWeight": 0.45, "hairDarkness": 0.15, "hairVolume": 0.8, "expressionNeutrality": 0.1, "contrast": 0.75, "angularity": 0.6, "warmth": 0.9, "symmetry": 0.6, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.7, "jawWidthRatio": 0.44, "jawAngle": 0.51, "chinLengthRatio": 0.41, "chinSharpness": 0.43, "foreheadWidthRatio": 0.41, "foreheadHeightRatio": 0.42, "cheekboneWidthRatio": 0.68, "faceHeightRatio": 0.35, "eyeSizeRatio": 0.85, "eyeSpacingRatio": 0.49, "eyeTilt": 0.52, "eyeRoundness": 0.8, "eyebrowThickness": 0.48, "eyebrowCurve": 0.86, "noseLengthRatio": 0.47, "noseWidthRatio": 0.5, "mouthWidthRatio": 0.63, "lipThickness": 0.73, "earSizeRatio": 0.5, "hairlineHeight": 0.53, "neckWidthRatio": 0.3, "stylizationIndex": 0.5 },
    "design_breakdown": { "communicates": ["Unignorable optimism", "Motion", "Approachability"], "through": ["maximum-warmth costume colour", "triangular hair over round face", "open-mouth default expression", "high-energy silhouette"] }
  },
  {
    "id": "violet-evergarden", "name": "Violet Evergarden", "gender": "female", "series": "Violet Evergarden",
    "creator": "Kana Akatsuki", "characterDesigner": "Akiko Takase", "studio": "Kyoto Animation", "franchise": "Violet Evergarden",
    "aliases": [], "publisher": "Kyoto Animation", "firstAppearance": "2015 (light novel)", "collection": "anime",
    "visual_traits": ["Doll-like symmetry", "Wide still eyes", "Long braided blond hair", "White gloves"],
    "design_language": ["Rebirth", "Restraint", "Grace"],
    "shape_language": "Soft verticals, ribbon curves",
    "primary_colors": ["#F3EEE4", "#20406B", "#D9B44A"],
    "silhouette": "Elegant column", "archetype": "The Reborn Weapon", "temperament": "Reserved",
    "keywords": ["gloves", "braids", "elegant", "still"],
    "description": "A former weapon redesigned in ribbons — the costume records the direction of change.",
    "profile": { "faceLength": 0.55, "jawSharpness": 0.35, "eyeNarrowness": 0.2, "browWeight": 0.3, "hairDarkness": 0.2, "hairVolume": 0.75, "expressionNeutrality": 0.9, "symmetry": 0.9, "contrast": 0.5, "angularity": 0.25, "warmth": 0.55, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.49, "jawWidthRatio": 0.4, "jawAngle": 0.47, "chinLengthRatio": 0.52, "chinSharpness": 0.4, "foreheadWidthRatio": 0.64, "foreheadHeightRatio": 0.56, "cheekboneWidthRatio": 0.49, "faceHeightRatio": 0.48, "eyeSizeRatio": 0.82, "eyeSpacingRatio": 0.72, "eyeTilt": 0.23, "eyeRoundness": 0.93, "eyebrowThickness": 0.26, "eyebrowCurve": 0.53, "noseLengthRatio": 0.56, "noseWidthRatio": 0.38, "mouthWidthRatio": 0.41, "lipThickness": 0.46, "earSizeRatio": 0.29, "hairlineHeight": 0.53, "neckWidthRatio": 0.46, "stylizationIndex": 0.5 },
    "design_breakdown": { "communicates": ["Grace over history of violence", "Emotional distance closing slowly"], "through": ["extreme symmetry", "soft silhouette on a rigid posture", "gloves staging the story at the hands", "one emerald accent"] }
  },
  {
    "id": "edward-elric", "name": "Edward Elric", "gender": "male", "series": "Fullmetal Alchemist",
    "creator": "Hiromu Arakawa", "characterDesigner": None, "studio": "Bones", "franchise": "Fullmetal Alchemist",
    "aliases": [], "publisher": "Square Enix", "firstAppearance": "2001 (manga)", "collection": "anime",
    "visual_traits": ["Golden braid", "Fierce round eyes", "Red coat", "Automail arm"],
    "design_language": ["Defiance", "Cost", "Brotherhood"],
    "shape_language": "Compact triangles",
    "primary_colors": ["#B3202C", "#111111", "#E8B33A"],
    "silhouette": "Small but flared coat", "archetype": "The Prodigy Who Paid", "temperament": "Fiery",
    "keywords": ["braid", "red coat", "short", "alchemy"],
    "description": "A short silhouette flared into largeness by the coat — stature as psychology.",
    "profile": { "faceLength": 0.45, "jawSharpness": 0.5, "eyeNarrowness": 0.3, "browWeight": 0.55, "hairDarkness": 0.25, "hairVolume": 0.65, "expressionNeutrality": 0.2, "contrast": 0.8, "angularity": 0.6, "warmth": 0.8, "symmetry": 0.6, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.61, "jawWidthRatio": 0.63, "jawAngle": 0.61, "chinLengthRatio": 0.45, "chinSharpness": 0.49, "foreheadWidthRatio": 0.47, "foreheadHeightRatio": 0.49, "cheekboneWidthRatio": 0.67, "faceHeightRatio": 0.49, "eyeSizeRatio": 0.74, "eyeSpacingRatio": 0.58, "eyeTilt": 0.58, "eyeRoundness": 0.81, "eyebrowThickness": 0.44, "eyebrowCurve": 0.77, "noseLengthRatio": 0.4, "noseWidthRatio": 0.38, "mouthWidthRatio": 0.56, "lipThickness": 0.67, "earSizeRatio": 0.15, "hairlineHeight": 0.53, "neckWidthRatio": 0.43, "stylizationIndex": 0.52 },
    "design_breakdown": { "communicates": ["Defiance of limits", "Visible cost of ambition"], "through": ["flamboyant coat compensating scale", "metal arm kept visible", "golden braid as signature break", "red/black/gold triad"] }
  },
  {
    "id": "goku", "name": "Son Goku", "gender": "male", "series": "Dragon Ball",
    "creator": "Akira Toriyama", "characterDesigner": None, "studio": "Toei Animation", "franchise": "Dragon Ball",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "1984 (manga)", "collection": "anime",
    "visual_traits": ["Instantly readable spiked hair", "Round friendly eyes", "Orange gi", "Broad grin"],
    "design_language": ["Joyful strength", "Simplicity", "Motion"],
    "shape_language": "Bold triangles on circles",
    "primary_colors": ["#F47B20", "#20469B", "#111111"],
    "silhouette": "Unmistakable spike crown", "archetype": "The Joyful Fighter", "temperament": "Cheerful",
    "keywords": ["spikes", "orange gi", "classic", "grin"],
    "description": "The most silhouette-recognisable head in animation — designed to survive weekly deadlines.",
    "profile": { "faceLength": 0.45, "jawSharpness": 0.55, "eyeNarrowness": 0.3, "browWeight": 0.5, "hairDarkness": 0.9, "hairVolume": 0.95, "expressionNeutrality": 0.2, "contrast": 0.75, "angularity": 0.7, "warmth": 0.85, "glasses": 0.0, "symmetry": 0.6 },
    "facialMetrics": { "faceShape": 0.61, "jawWidthRatio": 0.51, "jawAngle": 0.65, "chinLengthRatio": 0.57, "chinSharpness": 0.55, "foreheadWidthRatio": 0.51, "foreheadHeightRatio": 0.4, "cheekboneWidthRatio": 0.72, "faceHeightRatio": 0.38, "eyeSizeRatio": 0.77, "eyeSpacingRatio": 0.43, "eyeTilt": 0.61, "eyeRoundness": 0.75, "eyebrowThickness": 0.41, "eyebrowCurve": 0.71, "noseLengthRatio": 0.41, "noseWidthRatio": 0.39, "mouthWidthRatio": 0.47, "lipThickness": 0.7, "earSizeRatio": 0.65, "hairlineHeight": 0.57, "neckWidthRatio": 0.43, "stylizationIndex": 0.61 },
    "design_breakdown": { "communicates": ["Strength without menace", "Instant recognisability"], "through": ["a hair silhouette ownable at any size", "warm costume", "round facial base under sharp hair", "economy of line for weekly production"] }
  },
  {
    "id": "monkey-d-luffy", "name": "Monkey D. Luffy", "gender": "male", "series": "One Piece",
    "creator": "Eiichiro Oda", "characterDesigner": None, "studio": "Toei Animation", "franchise": "One Piece",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "1997 (manga)", "collection": "anime",
    "visual_traits": ["Straw hat", "Huge round eyes", "Scar under eye", "Rubbery grin"],
    "design_language": ["Freedom", "Promise", "Appetite for life"],
    "shape_language": "Circles",
    "primary_colors": ["#D22B2B", "#2B65D2", "#F2D16B"],
    "silhouette": "Hat-crowned and loose", "archetype": "The Free Spirit", "temperament": "Unburdened",
    "keywords": ["straw hat", "grin", "scar", "simple"],
    "description": "The hat is a debt worn on the head — a promise that doubles as the silhouette's signature break.",
    "profile": { "faceLength": 0.4, "jawSharpness": 0.3, "eyeNarrowness": 0.15, "browWeight": 0.4, "hairDarkness": 0.9, "hairVolume": 0.5, "expressionNeutrality": 0.05, "contrast": 0.7, "angularity": 0.25, "warmth": 0.8, "glasses": 0.0, "symmetry": 0.6 },
    "facialMetrics": { "faceShape": 0.53, "jawWidthRatio": 0.48, "jawAngle": 0.34, "chinLengthRatio": 0.48, "chinSharpness": 0.45, "foreheadWidthRatio": 0.61, "foreheadHeightRatio": 0.45, "cheekboneWidthRatio": 0.42, "faceHeightRatio": 0.47, "eyeSizeRatio": 0.93, "eyeSpacingRatio": 0.59, "eyeTilt": 0.33, "eyeRoundness": 0.81, "eyebrowThickness": 0.43, "eyebrowCurve": 0.69, "noseLengthRatio": 0.33, "noseWidthRatio": 0.38, "mouthWidthRatio": 0.53, "lipThickness": 0.72, "earSizeRatio": 0.18, "hairlineHeight": 0.4, "neckWidthRatio": 0.33, "stylizationIndex": 0.94 },
    "design_breakdown": { "communicates": ["Total freedom", "Loyalty to a promise"], "through": ["circle-family everything", "the outline-breaking hat", "two scars with stories", "a design drawable ten thousand times"] }
  },
  {
    "id": "l-lawliet", "name": "L Lawliet", "gender": "male", "series": "Death Note",
    "creator": "Tsugumi Ohba", "characterDesigner": "Takeshi Obata", "studio": "Madhouse", "franchise": "Death Note",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "2003 (manga)", "collection": "anime",
    "visual_traits": ["Deep-set shadowed eyes", "Unkempt black hair", "Hunched posture", "Pale palette"],
    "design_language": ["Intellect", "Eccentricity", "Insomnia"],
    "shape_language": "Collapsed verticals",
    "primary_colors": ["#FFFFFF", "#1A1A1A", "#8E9BA8"],
    "silhouette": "Question-mark hunch", "archetype": "The Detective", "temperament": "Detached",
    "keywords": ["shadowed eyes", "hunched", "genius", "monochrome"],
    "description": "Posture as characterisation — the smartest figure in the room drawn as a folded question mark.",
    "profile": { "faceLength": 0.6, "jawSharpness": 0.45, "eyeNarrowness": 0.35, "browWeight": 0.35, "hairDarkness": 0.95, "hairVolume": 0.75, "expressionNeutrality": 0.85, "symmetry": 0.4, "contrast": 0.9, "angularity": 0.4, "warmth": 0.2, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.43, "jawWidthRatio": 0.6, "jawAngle": 0.45, "chinLengthRatio": 0.57, "chinSharpness": 0.4, "foreheadWidthRatio": 0.64, "foreheadHeightRatio": 0.44, "cheekboneWidthRatio": 0.41, "faceHeightRatio": 0.64, "eyeSizeRatio": 0.77, "eyeSpacingRatio": 0.42, "eyeTilt": 0.35, "eyeRoundness": 0.75, "eyebrowThickness": 0.36, "eyebrowCurve": 0.32, "noseLengthRatio": 0.39, "noseWidthRatio": 0.39, "mouthWidthRatio": 0.28, "lipThickness": 0.29, "earSizeRatio": 0.65, "hairlineHeight": 0.58, "neckWidthRatio": 0.39, "stylizationIndex": 0.42 },
    "design_breakdown": { "communicates": ["Analysis over presentation", "Otherness"], "through": ["eye bags as permanent feature", "monochrome costume", "broken posture line", "hair that refuses grooming"] }
  },
  {
    "id": "sailor-moon", "name": "Usagi Tsukino (Sailor Moon)", "gender": "female", "series": "Sailor Moon",
    "creator": "Naoko Takeuchi", "characterDesigner": None, "studio": "Toei Animation", "franchise": "Sailor Moon",
    "aliases": [], "publisher": "Kodansha", "firstAppearance": "1991 (manga)", "collection": "anime",
    "visual_traits": ["Twin odango buns", "Enormous expressive eyes", "Flowing twin tails", "Bright palette"],
    "design_language": ["Hope", "Femininity as power", "Transformation"],
    "shape_language": "Circles and crescents",
    "primary_colors": ["#F7D354", "#274A9C", "#E5518D"],
    "silhouette": "Twin-tail crescents", "archetype": "The Chosen Heart", "temperament": "Openhearted",
    "keywords": ["buns", "twin tails", "magical girl", "bright"],
    "description": "A silhouette readable from orbit — twin buns and tails that survive any art style shift.",
    "profile": { "faceLength": 0.35, "jawSharpness": 0.2, "eyeNarrowness": 0.05, "browWeight": 0.3, "hairDarkness": 0.15, "hairVolume": 0.95, "expressionNeutrality": 0.1, "symmetry": 0.85, "contrast": 0.65, "angularity": 0.15, "warmth": 0.8, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.36, "jawWidthRatio": 0.36, "jawAngle": 0.44, "chinLengthRatio": 0.49, "chinSharpness": 0.32, "foreheadWidthRatio": 0.62, "foreheadHeightRatio": 0.38, "cheekboneWidthRatio": 0.29, "faceHeightRatio": 0.34, "eyeSizeRatio": 0.97, "eyeSpacingRatio": 0.61, "eyeTilt": 0.24, "eyeRoundness": 0.91, "eyebrowThickness": 0.24, "eyebrowCurve": 0.63, "noseLengthRatio": 0.41, "noseWidthRatio": 0.26, "mouthWidthRatio": 0.55, "lipThickness": 0.65, "earSizeRatio": 0.23, "hairlineHeight": 0.56, "neckWidthRatio": 0.36, "stylizationIndex": 0.67 },
    "design_breakdown": { "communicates": ["Radiant hope", "Approachable heroism"], "through": ["maximum-circle shape family", "signature twin-bun break", "saturated accents on white", "eyes as the design's stage"] }
  },
  {
    "id": "spike-spiegel", "name": "Spike Spiegel", "gender": "male", "series": "Cowboy Bebop",
    "creator": "Hajime Yatate / Shinichiro Watanabe", "characterDesigner": "Toshihiro Kawamoto", "studio": "Sunrise", "franchise": "Cowboy Bebop",
    "aliases": [], "publisher": "Sunrise", "firstAppearance": "1998 (anime)", "collection": "anime",
    "visual_traits": ["Lanky frame", "Heavy-lidded eyes", "Fluffy dark mop", "Loose suit"],
    "design_language": ["Cool detachment", "Jazz", "Past regrets"],
    "shape_language": "Loose verticals",
    "primary_colors": ["#27408B", "#F2E1C1", "#5B3A29"],
    "silhouette": "Slouched noodle", "archetype": "The Drifter", "temperament": "Laconic",
    "keywords": ["suit", "slouch", "cool", "retro"],
    "description": "The slouch is the story: skill so complete it never needs to stand up straight.",
    "profile": { "faceLength": 0.75, "jawSharpness": 0.6, "eyeNarrowness": 0.7, "browWeight": 0.45, "hairDarkness": 0.85, "hairVolume": 0.8, "expressionNeutrality": 0.7, "symmetry": 0.45, "contrast": 0.55, "angularity": 0.5, "warmth": 0.5, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.58, "jawWidthRatio": 0.6, "jawAngle": 0.58, "chinLengthRatio": 0.6, "chinSharpness": 0.54, "foreheadWidthRatio": 0.6, "foreheadHeightRatio": 0.66, "cheekboneWidthRatio": 0.58, "faceHeightRatio": 0.78, "eyeSizeRatio": 0.52, "eyeSpacingRatio": 0.58, "eyeTilt": 0.55, "eyeRoundness": 0.52, "eyebrowThickness": 0.42, "eyebrowCurve": 0.57, "noseLengthRatio": 0.54, "noseWidthRatio": 0.31, "mouthWidthRatio": 0.29, "lipThickness": 0.47, "earSizeRatio": 0.29, "hairlineHeight": 0.58, "neckWidthRatio": 0.4, "stylizationIndex": 0.3 },
    "design_breakdown": { "communicates": ["Effortlessness", "Melancholy under cool"], "through": ["relaxed line over athletic frame", "asymmetric hair mass", "lidded eyes", "workwear-loose tailoring"] }
  },
  {
    "id": "nezuko-kamado", "name": "Nezuko Kamado", "gender": "female", "series": "Demon Slayer",
    "creator": "Koyoharu Gotouge", "characterDesigner": None, "studio": "ufotable", "franchise": "Demon Slayer",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "2016 (manga)", "collection": "anime",
    "visual_traits": ["Bamboo muzzle", "Huge gradient eyes", "Long flowing hair", "Pink kimono"],
    "design_language": ["Innocence preserved", "Duality", "Protection"],
    "shape_language": "Soft circles",
    "primary_colors": ["#E8A0BF", "#3E2723", "#69B076"],
    "silhouette": "Flowing with ribbon breaks", "archetype": "The Protected Protector", "temperament": "Gentle",
    "keywords": ["bamboo", "pink", "gradient hair", "gentle"],
    "description": "The muzzle removes speech, so the entire design acts through eyes and hair motion.",
    "profile": { "faceLength": 0.4, "jawSharpness": 0.25, "eyeNarrowness": 0.1, "browWeight": 0.35, "hairDarkness": 0.75, "hairVolume": 0.85, "expressionNeutrality": 0.45, "symmetry": 0.8, "contrast": 0.6, "angularity": 0.2, "warmth": 0.75, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.37, "jawWidthRatio": 0.39, "jawAngle": 0.39, "chinLengthRatio": 0.47, "chinSharpness": 0.3, "foreheadWidthRatio": 0.65, "foreheadHeightRatio": 0.51, "cheekboneWidthRatio": 0.43, "faceHeightRatio": 0.47, "eyeSizeRatio": 0.89, "eyeSpacingRatio": 0.54, "eyeTilt": 0.19, "eyeRoundness": 0.97, "eyebrowThickness": 0.26, "eyebrowCurve": 0.72, "noseLengthRatio": 0.31, "noseWidthRatio": 0.26, "mouthWidthRatio": 0.54, "lipThickness": 0.71, "earSizeRatio": 0.65, "hairlineHeight": 0.57, "neckWidthRatio": 0.33, "stylizationIndex": 0.47 },
    "design_breakdown": { "communicates": ["Innocence inside danger", "Wordless emotion"], "through": ["eyes enlarged to carry all acting", "soft palette against demon lore", "the bamboo as unforgettable accessory", "hair as motion device"] }
  },
  {
    "id": "kaneki-ken", "name": "Ken Kaneki", "gender": "male", "series": "Tokyo Ghoul",
    "creator": "Sui Ishida", "characterDesigner": None, "studio": "Pierrot", "franchise": "Tokyo Ghoul",
    "aliases": [], "publisher": "Shueisha", "firstAppearance": "2011 (manga)", "collection": "anime",
    "visual_traits": ["White hair transformation", "One hidden eye", "Slender frame", "Mask"],
    "design_language": ["Duality", "Loss of self", "Rebirth through pain"],
    "shape_language": "Fragile verticals",
    "primary_colors": ["#FFFFFF", "#111111", "#C42B2B"],
    "silhouette": "Slim, mask-broken", "archetype": "The Transformed", "temperament": "Haunted",
    "keywords": ["white hair", "mask", "eyepatch", "duality"],
    "description": "Hair colour as chapter marker — the design tracks trauma in value inversion.",
    "profile": { "faceLength": 0.6, "jawSharpness": 0.5, "eyeNarrowness": 0.4, "browWeight": 0.35, "hairDarkness": 0.3, "hairVolume": 0.6, "expressionNeutrality": 0.65, "symmetry": 0.5, "contrast": 0.9, "angularity": 0.5, "warmth": 0.25, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.6, "jawWidthRatio": 0.61, "jawAngle": 0.48, "chinLengthRatio": 0.5, "chinSharpness": 0.45, "foreheadWidthRatio": 0.54, "foreheadHeightRatio": 0.51, "cheekboneWidthRatio": 0.47, "faceHeightRatio": 0.64, "eyeSizeRatio": 0.65, "eyeSpacingRatio": 0.48, "eyeTilt": 0.48, "eyeRoundness": 0.79, "eyebrowThickness": 0.28, "eyebrowCurve": 0.33, "noseLengthRatio": 0.52, "noseWidthRatio": 0.31, "mouthWidthRatio": 0.4, "lipThickness": 0.49, "earSizeRatio": 0.48, "hairlineHeight": 0.48, "neckWidthRatio": 0.5, "stylizationIndex": 0.43 },
    "design_breakdown": { "communicates": ["Identity fracture", "Before/after in one face"], "through": ["black-to-white hair inversion", "asymmetric eye reveal", "mask as second face", "red confined to accents"] }
  },
  {
    "id": "zero-two", "name": "Zero Two", "gender": "female", "series": "DARLING in the FRANXX",
    "creator": "A-1 Pictures / Trigger", "characterDesigner": "Akira Amemiya", "studio": "Trigger / A-1", "franchise": "DARLING in the FRANXX",
    "aliases": [], "publisher": "A-1 Pictures / Trigger", "firstAppearance": "2018 (anime)", "collection": "anime",
    "visual_traits": ["Long pink hair", "Small horns", "Teal eyes", "Confident smile"],
    "design_language": ["Otherness", "Allure", "Hunger for life"],
    "shape_language": "Long S-curves",
    "primary_colors": ["#F48FB1", "#B71C1C", "#26A69A"],
    "silhouette": "Long-haired arc", "archetype": "The Outsider", "temperament": "Magnetic",
    "keywords": ["pink hair", "horns", "confident", "long hair"],
    "description": "Two tiny horns do the world-building; everything else is designed charm.",
    "profile": { "faceLength": 0.6, "jawSharpness": 0.45, "eyeNarrowness": 0.4, "browWeight": 0.35, "hairDarkness": 0.2, "hairVolume": 0.9, "expressionNeutrality": 0.3, "symmetry": 0.75, "contrast": 0.6, "angularity": 0.3, "warmth": 0.7, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.51, "jawWidthRatio": 0.48, "jawAngle": 0.41, "chinLengthRatio": 0.47, "chinSharpness": 0.4, "foreheadWidthRatio": 0.55, "foreheadHeightRatio": 0.59, "cheekboneWidthRatio": 0.46, "faceHeightRatio": 0.6, "eyeSizeRatio": 0.63, "eyeSpacingRatio": 0.58, "eyeTilt": 0.34, "eyeRoundness": 0.71, "eyebrowThickness": 0.29, "eyebrowCurve": 0.53, "noseLengthRatio": 0.44, "noseWidthRatio": 0.24, "mouthWidthRatio": 0.62, "lipThickness": 0.51, "earSizeRatio": 0.36, "hairlineHeight": 0.65, "neckWidthRatio": 0.33, "stylizationIndex": 0.56 },
    "design_breakdown": { "communicates": ["Non-human grace", "Confidence"], "through": ["signature horn break on an elegant outline", "hair as the silhouette's main mass", "warm hair against cool eyes", "relaxed smile default"] }
  },
  {
    "id": "cloud-strife", "name": "Cloud Strife", "gender": "male", "series": "Final Fantasy VII",
    "creator": "Hironobu Sakaguchi", "characterDesigner": "Tetsuya Nomura", "studio": "Square Enix", "franchise": "Final Fantasy",
    "aliases": [], "publisher": "Square Enix", "firstAppearance": "1997 (Final Fantasy VII)", "collection": "games",
    "visual_traits": ["Gravity-defying blond spikes", "Glowing blue eyes", "Oversized sword", "Guarded look"],
    "design_language": ["Burden", "Iconic silhouette", "Guardedness"],
    "shape_language": "Aggressive triangles",
    "primary_colors": ["#2C3E70", "#E8D44D", "#8892A0"],
    "silhouette": "Spikes plus greatsword", "archetype": "The Reluctant Hero", "temperament": "Withdrawn",
    "keywords": ["spiky blond", "big sword", "soldier", "guarded"],
    "description": "The sword outweighs the man on purpose — burden made literal in silhouette.",
    "profile": { "faceLength": 0.6, "jawSharpness": 0.7, "eyeNarrowness": 0.55, "browWeight": 0.45, "hairDarkness": 0.15, "hairVolume": 0.9, "expressionNeutrality": 0.75, "contrast": 0.75, "angularity": 0.85, "warmth": 0.4, "symmetry": 0.7, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.75, "jawWidthRatio": 0.61, "jawAngle": 0.63, "chinLengthRatio": 0.64, "chinSharpness": 0.69, "foreheadWidthRatio": 0.47, "foreheadHeightRatio": 0.61, "cheekboneWidthRatio": 0.73, "faceHeightRatio": 0.66, "eyeSizeRatio": 0.62, "eyeSpacingRatio": 0.53, "eyeTilt": 0.82, "eyeRoundness": 0.59, "eyebrowThickness": 0.39, "eyebrowCurve": 0.33, "noseLengthRatio": 0.39, "noseWidthRatio": 0.42, "mouthWidthRatio": 0.29, "lipThickness": 0.37, "earSizeRatio": 0.22, "hairlineHeight": 0.55, "neckWidthRatio": 0.41, "stylizationIndex": 0.26 },
    "design_breakdown": { "communicates": ["Weight carried alone", "Instant recognisability"], "through": ["hair spikes ownable in two strokes", "weapon-to-body ratio", "cool palette with one warm signal", "guarded eye framing"] }
  },
  {
    "id": "aloy", "name": "Aloy", "gender": "female", "series": "Horizon",
    "creator": "Guerrilla Games", "characterDesigner": None, "studio": "Guerrilla Games", "franchise": "Horizon",
    "aliases": [], "publisher": "Sony Interactive Entertainment", "firstAppearance": "2017 (Horizon Zero Dawn)", "collection": "games",
    "visual_traits": ["Voluminous red braids", "Freckles", "Determined brow", "Tribal-tech layers"],
    "design_language": ["Curiosity", "Resilience", "Nature-meets-machine"],
    "shape_language": "Organic triangles",
    "primary_colors": ["#B4531F", "#3E6B4F", "#CDBBA0"],
    "silhouette": "Braid-crowned explorer", "archetype": "The Seeker", "temperament": "Determined",
    "keywords": ["red hair", "braids", "freckles", "hunter"],
    "description": "Hair engineered as silhouette: braids that read at horizon distance.",
    "profile": { "faceLength": 0.5, "jawSharpness": 0.45, "eyeNarrowness": 0.35, "browWeight": 0.6, "hairDarkness": 0.45, "hairVolume": 0.9, "expressionNeutrality": 0.45, "symmetry": 0.6, "contrast": 0.6, "angularity": 0.5, "warmth": 0.8, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.6, "jawWidthRatio": 0.45, "jawAngle": 0.51, "chinLengthRatio": 0.5, "chinSharpness": 0.52, "foreheadWidthRatio": 0.57, "foreheadHeightRatio": 0.46, "cheekboneWidthRatio": 0.57, "faceHeightRatio": 0.47, "eyeSizeRatio": 0.65, "eyeSpacingRatio": 0.55, "eyeTilt": 0.59, "eyeRoundness": 0.85, "eyebrowThickness": 0.62, "eyebrowCurve": 0.8, "noseLengthRatio": 0.5, "noseWidthRatio": 0.38, "mouthWidthRatio": 0.5, "lipThickness": 0.67, "earSizeRatio": 0.18, "hairlineHeight": 0.54, "neckWidthRatio": 0.33, "stylizationIndex": 0.15 },
    "design_breakdown": { "communicates": ["Self-reliant curiosity", "Warmth in a hard world"], "through": ["warm hair against cool machine world", "layered functional costume", "freckles as texture honesty", "forward-set brow"] }
  },
  {
    "id": "link", "name": "Link", "gender": "male", "series": "The Legend of Zelda",
    "creator": "Nintendo", "characterDesigner": "Satoru Takizawa", "studio": "Nintendo", "franchise": "Zelda",
    "aliases": [], "publisher": "Nintendo", "firstAppearance": "1986 (The Legend of Zelda)", "collection": "games",
    "visual_traits": ["Pointed ears", "Neat blond hair", "Clear watchful eyes", "Green/blue hero wear"],
    "design_language": ["Courage", "Silence", "Readiness"],
    "shape_language": "Clean triangles",
    "primary_colors": ["#4F7A45", "#3F6FB4", "#E9DFA9"],
    "silhouette": "Trim adventurer", "archetype": "The Silent Hero", "temperament": "Composed",
    "keywords": ["elf ears", "hero", "silent", "tidy"],
    "description": "A hero who never speaks, so the design keeps every line alert and legible.",
    "profile": { "faceLength": 0.5, "jawSharpness": 0.5, "eyeNarrowness": 0.4, "browWeight": 0.4, "hairDarkness": 0.2, "hairVolume": 0.6, "expressionNeutrality": 0.7, "symmetry": 0.75, "contrast": 0.55, "angularity": 0.55, "warmth": 0.55, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.56, "jawWidthRatio": 0.56, "jawAngle": 0.6, "chinLengthRatio": 0.57, "chinSharpness": 0.45, "foreheadWidthRatio": 0.43, "foreheadHeightRatio": 0.45, "cheekboneWidthRatio": 0.66, "faceHeightRatio": 0.5, "eyeSizeRatio": 0.62, "eyeSpacingRatio": 0.51, "eyeTilt": 0.62, "eyeRoundness": 0.73, "eyebrowThickness": 0.37, "eyebrowCurve": 0.47, "noseLengthRatio": 0.36, "noseWidthRatio": 0.49, "mouthWidthRatio": 0.4, "lipThickness": 0.54, "earSizeRatio": 0.28, "hairlineHeight": 0.63, "neckWidthRatio": 0.45, "stylizationIndex": 0.32 },
    "design_breakdown": { "communicates": ["Quiet readiness", "Timeless heroism"], "through": ["ear silhouette break", "kept-simple face for player projection", "triadic hero palette", "posture always slightly forward"] }
  },
  {
    "id": "2b", "name": "2B", "gender": "female", "series": "NieR: Automata",
    "creator": "Yoko Taro", "characterDesigner": "Akihiko Yoshida", "studio": "PlatinumGames / Square Enix", "franchise": "NieR",
    "aliases": [], "publisher": "Square Enix", "firstAppearance": "2010 (NieR)", "collection": "games",
    "visual_traits": ["Blindfold visor", "White bob", "Black gothic dress", "Composed mouth"],
    "design_language": ["Elegy", "Duty", "Concealed feeling"],
    "shape_language": "Gothic verticals",
    "primary_colors": ["#111111", "#EDEDED", "#B08D57"],
    "silhouette": "Monochrome column", "archetype": "The Duty-Bound", "temperament": "Composed",
    "keywords": ["blindfold", "white hair", "black dress", "android"],
    "description": "Eyes removed from the design equation — grief performed entirely by the mouth and stance.",
    "profile": { "faceLength": 0.55, "jawSharpness": 0.45, "eyeNarrowness": 0.5, "browWeight": 0.3, "hairDarkness": 0.1, "hairVolume": 0.55, "expressionNeutrality": 0.9, "symmetry": 0.85, "contrast": 0.95, "angularity": 0.45, "glasses": 0.85, "warmth": 0.3 },
    "facialMetrics": { "faceShape": 0.57, "jawWidthRatio": 0.48, "jawAngle": 0.56, "chinLengthRatio": 0.62, "chinSharpness": 0.53, "foreheadWidthRatio": 0.5, "foreheadHeightRatio": 0.49, "cheekboneWidthRatio": 0.57, "faceHeightRatio": 0.56, "eyeSizeRatio": 0.55, "eyeSpacingRatio": 0.63, "eyeTilt": 0.41, "eyeRoundness": 0.61, "eyebrowThickness": 0.32, "eyebrowCurve": 0.37, "noseLengthRatio": 0.53, "noseWidthRatio": 0.3, "mouthWidthRatio": 0.36, "lipThickness": 0.51, "earSizeRatio": 0.17, "hairlineHeight": 0.48, "neckWidthRatio": 0.49, "stylizationIndex": 0.19 },
    "design_breakdown": { "communicates": ["Mourning", "Machine grace"], "through": ["strict black/white value plan", "covered eyes concentrating emotion in the mouth", "lace texture against combat function", "perfect symmetry"] }
  },
  {
    "id": "batman", "name": "Batman", "gender": "male", "series": "DC Comics",
    "creator": "Bob Kane & Bill Finger", "characterDesigner": None, "studio": "DC", "franchise": "Batman",
    "aliases": [], "publisher": "DC Comics", "firstAppearance": "1939 (Detective Comics #27)", "collection": "comics",
    "visual_traits": ["Cowl ears", "Hidden eyes", "Square jaw", "Cape silhouette"],
    "design_language": ["Fear as tool", "Discipline", "Theatre"],
    "shape_language": "Hard triangles on a square jaw",
    "primary_colors": ["#101318", "#3A4048", "#F4C542"],
    "silhouette": "Cape-and-ears icon", "archetype": "The Dark Knight", "temperament": "Grim",
    "keywords": ["cowl", "cape", "jaw", "night"],
    "description": "The exposed jaw is the design's only humanity — everything else is engineered dread.",
    "profile": { "faceLength": 0.6, "jawSharpness": 0.9, "eyeNarrowness": 0.85, "browWeight": 0.7, "hairDarkness": 0.9, "hairVolume": 0.5, "expressionNeutrality": 0.9, "symmetry": 0.8, "contrast": 0.9, "angularity": 0.9, "warmth": 0.2, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.88, "jawWidthRatio": 0.84, "jawAngle": 0.77, "chinLengthRatio": 0.52, "chinSharpness": 0.72, "foreheadWidthRatio": 0.35, "foreheadHeightRatio": 0.63, "cheekboneWidthRatio": 0.73, "faceHeightRatio": 0.65, "eyeSizeRatio": 0.28, "eyeSpacingRatio": 0.69, "eyeTilt": 0.67, "eyeRoundness": 0.49, "eyebrowThickness": 0.67, "eyebrowCurve": 0.37, "noseLengthRatio": 0.56, "noseWidthRatio": 0.47, "mouthWidthRatio": 0.38, "lipThickness": 0.44, "earSizeRatio": 0.33, "hairlineHeight": 0.59, "neckWidthRatio": 0.45, "stylizationIndex": 0.31 },
    "design_breakdown": { "communicates": ["Intimidation", "Unbreakable will"], "through": ["ear-and-cape silhouette readable in darkness", "hidden eyes", "the jaw as the single human element", "near-monochrome palette"] }
  },
  {
    "id": "spider-man", "name": "Spider-Man", "gender": "male", "series": "Marvel Comics",
    "creator": "Stan Lee & Steve Ditko", "characterDesigner": None, "studio": "Marvel", "franchise": "Spider-Man",
    "aliases": [], "publisher": "Marvel Comics", "firstAppearance": "1962 (Amazing Fantasy #15)", "collection": "comics",
    "visual_traits": ["Full mask", "Expressive eye shapes", "Lean build", "Web texture"],
    "design_language": ["Agility", "Youth", "Relatability"],
    "shape_language": "Dynamic curves",
    "primary_colors": ["#D62E33", "#2451A4", "#0F0F0F"],
    "silhouette": "Lean acrobat", "archetype": "The Friendly Hero", "temperament": "Quick",
    "keywords": ["mask", "red blue", "webs", "agile"],
    "description": "A masked face that still out-acts most bare ones — eye shapes designed as a logo with moods.",
    "profile": { "faceLength": 0.5, "jawSharpness": 0.5, "eyeNarrowness": 0.35, "browWeight": 0.4, "hairDarkness": 0.5, "hairVolume": 0.35, "expressionNeutrality": 0.3, "symmetry": 0.8, "contrast": 0.85, "angularity": 0.5, "glasses": 0.6, "warmth": 0.65 },
    "facialMetrics": { "faceShape": 0.48, "jawWidthRatio": 0.54, "jawAngle": 0.43, "chinLengthRatio": 0.58, "chinSharpness": 0.56, "foreheadWidthRatio": 0.6, "foreheadHeightRatio": 0.46, "cheekboneWidthRatio": 0.64, "faceHeightRatio": 0.47, "eyeSizeRatio": 0.66, "eyeSpacingRatio": 0.67, "eyeTilt": 0.4, "eyeRoundness": 0.76, "eyebrowThickness": 0.41, "eyebrowCurve": 0.64, "noseLengthRatio": 0.39, "noseWidthRatio": 0.32, "mouthWidthRatio": 0.48, "lipThickness": 0.65, "earSizeRatio": 0.28, "hairlineHeight": 0.37, "neckWidthRatio": 0.33, "stylizationIndex": 0.35 },
    "design_breakdown": { "communicates": ["Energy", "Approachability at every reading distance"], "through": ["warm-advance/cool-recede colour split", "graphic eye objects", "web-lines doubling as form wireframe", "three deliberate reading distances"] }
  },
  {
    "id": "miles-morales", "name": "Miles Morales", "gender": "male", "series": "Spider-Verse",
    "creator": "Stan Lee & Steve Ditko", "characterDesigner": None, "studio": "Sony Pictures Animation", "franchise": "Spider-Man",
    "aliases": [], "publisher": "Marvel Comics", "firstAppearance": "1962 (Amazing Fantasy #15)", "collection": "animation",
    "visual_traits": ["Short curly hair", "Expressive brows", "Sneakers with suit", "Spray-paint accents"],
    "design_language": ["Becoming", "Street style", "Rhythm"],
    "shape_language": "Rounded rectangles",
    "primary_colors": ["#0F0F0F", "#D62E33", "#7F5AF0"],
    "silhouette": "Sneaker-grounded teen", "archetype": "The New Inheritor", "temperament": "Earnest",
    "keywords": ["curls", "sneakers", "graffiti", "teen"],
    "description": "Untied laces and a hand-sprayed suit — a hero explicitly drawn mid-becoming.",
    "profile": { "faceLength": 0.5, "jawSharpness": 0.4, "eyeNarrowness": 0.3, "browWeight": 0.6, "hairDarkness": 0.9, "hairVolume": 0.7, "expressionNeutrality": 0.25, "symmetry": 0.6, "contrast": 0.8, "angularity": 0.4, "warmth": 0.7, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.53, "jawWidthRatio": 0.51, "jawAngle": 0.43, "chinLengthRatio": 0.45, "chinSharpness": 0.43, "foreheadWidthRatio": 0.57, "foreheadHeightRatio": 0.59, "cheekboneWidthRatio": 0.48, "faceHeightRatio": 0.57, "eyeSizeRatio": 0.78, "eyeSpacingRatio": 0.63, "eyeTilt": 0.37, "eyeRoundness": 0.85, "eyebrowThickness": 0.51, "eyebrowCurve": 0.71, "noseLengthRatio": 0.4, "noseWidthRatio": 0.4, "mouthWidthRatio": 0.51, "lipThickness": 0.65, "earSizeRatio": 0.31, "hairlineHeight": 0.65, "neckWidthRatio": 0.46, "stylizationIndex": 0.32 },
    "design_breakdown": { "communicates": ["Growth in progress", "Personal style as identity"], "through": ["black suit breaking the inherited palette", "sneakers against spandex", "animated-on-twos motion signature", "graffiti-texture accents"] }
  },
  {
    "id": "elsa", "name": "Elsa", "gender": "female", "series": "Frozen",
    "creator": "Chris Buck & Jennifer Lee", "characterDesigner": None, "studio": "Walt Disney Animation", "franchise": "Frozen",
    "aliases": [], "publisher": "Walt Disney Animation Studios", "firstAppearance": "2013 (film)", "collection": "animation",
    "visual_traits": ["Platinum side braid", "Almond eyes", "Poised chin", "Ice-blue palette"],
    "design_language": ["Contained power", "Poise", "Release"],
    "shape_language": "Elegant verticals and crystals",
    "primary_colors": ["#A8DDF0", "#F2F6FA", "#5A79B8"],
    "silhouette": "Column with braid break", "archetype": "The Contained Queen", "temperament": "Reserved-then-free",
    "keywords": ["braid", "ice", "queen", "poised"],
    "description": "The braid moving from pinned to loose is the whole arc, drawn in hair.",
    "profile": { "faceLength": 0.6, "jawSharpness": 0.45, "eyeNarrowness": 0.35, "browWeight": 0.35, "hairDarkness": 0.05, "hairVolume": 0.7, "expressionNeutrality": 0.6, "symmetry": 0.8, "contrast": 0.5, "angularity": 0.35, "warmth": 0.25, "glasses": 0.0 },
    "facialMetrics": { "faceShape": 0.58, "jawWidthRatio": 0.52, "jawAngle": 0.57, "chinLengthRatio": 0.53, "chinSharpness": 0.45, "foreheadWidthRatio": 0.56, "foreheadHeightRatio": 0.55, "cheekboneWidthRatio": 0.4, "faceHeightRatio": 0.58, "eyeSizeRatio": 0.64, "eyeSpacingRatio": 0.68, "eyeTilt": 0.33, "eyeRoundness": 0.84, "eyebrowThickness": 0.25, "eyebrowCurve": 0.35, "noseLengthRatio": 0.42, "noseWidthRatio": 0.24, "mouthWidthRatio": 0.47, "lipThickness": 0.37, "earSizeRatio": 0.17, "hairlineHeight": 0.53, "neckWidthRatio": 0.37, "stylizationIndex": 0.27 },
    "design_breakdown": { "communicates": ["Power held in check", "Transformation"], "through": ["cool monochrome palette", "hair state as story state", "crystal shape-language", "posture from pinned to fluid"] }
  }
]
